title: Spatial Database Design
description: Prof. Hachadoorian | Fall 2023
# theme: jekyll-theme-cayman
# theme: jekyll-theme-slate
# theme: jekyll-theme-merlot
# theme: jekyll-theme-dinky
remote_theme: chrisrhymes/bulma-clean-theme

titles_from_headings:
  enabled: false

defaults:
  
  -
    scope:
      path: ""
      type: "pages"
    values:
      title: Spatial Database Design
      subtitle: Fall 2023
      layout: page
      show_sidebar: false
      menubar: course_menu
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Lee Hachadoorian"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

